
export const ScoreCard = {
    "matches": [
      {
        "event_status": "Match Ended",
        "series_id": "2957",
        "event_is_daynight": "true",
        "event_state": "R",
        "result_code": "W",
        "event_islinkable": "true",
        "event_status_id": "114",
        "result_sub_code": "",
        "event_priority": "",
        "event_day": "",
        "league_code": "indian_domestic",
        "venue_id": "168",
        "event_sub_status": "ARCS Andheri beat North Mumbai Panthers by 23 runs",
        "event_livecoverage": "true",
        "event_duration_left": "",
        "game_id": "mnzmnt03112018186400",
        "participants": [
          {
            "name": "North Mumbai Panthers",
            "short_name": "NMP",
            "id": "1629",
            "value": "141 (19.1)",
            "now": "true"
          },
          {
            "name": "ARCS Andheri",
            "short_name": "AA",
            "id": "1631",
            "value": "164/7 (20)",
            "highlight": "true",
            "firstup": "true"
          }
        ],
        "tour_id": "876",
        "end_date": "2018-03-11T19:30+05:30",
        "venue_gmt_offset": "+05:30",
        "winning_margin": "23 runs",
        "venue_name": "Wankhede Stadium, Mumbai",
        "event_group": "",
        "event_name": "Match 1",
        "event_session": "",
        "series_name": "T20 Mumbai, 2018",
        "sport": "cricket",
        "tour_name": "T20 Mumbai, 2018",
        "start_date": "2018-03-11T15:30+05:30",
        "event_format": "t20",
        "event_stage": "league"
      },
      {
        "event_status": "Match Ended",
        "series_id": "2957",
        "event_is_daynight": "true",
        "event_state": "R",
        "result_code": "W",
        "event_islinkable": "true",
        "event_status_id": "114",
        "result_sub_code": "",
        "event_priority": "",
        "event_day": "",
        "league_code": "indian_domestic",
        "venue_id": "168",
        "event_sub_status": "Triumph Knights Mumbai North East beat SoBo SuperSonics by 4 wickets",
        "event_livecoverage": "true",
        "event_duration_left": "",
        "game_id": "msznte03112018186401",
        "participants": [
          {
            "name": "SoBo SuperSonics",
            "short_name": "SS",
            "id": "1634",
            "value": "184/7 (20)",
            "firstup": "true"
          },
          {
            "name": "Triumph Knights Mumbai North East",
            "short_name": "TKMNE",
            "id": "1632",
            "value": "186/6 (19.4)",
            "now": "true",
            "highlight": "true"
          }
        ],
        "tour_id": "876",
        "end_date": "2018-03-11T23:30+05:30",
        "venue_gmt_offset": "+05:30",
        "winning_margin": "4 wickets",
        "venue_name": "Wankhede Stadium, Mumbai",
        "event_group": "",
        "event_name": "Match 2",
        "event_session": "",
        "series_name": "T20 Mumbai, 2018",
        "sport": "cricket",
        "tour_name": "T20 Mumbai, 2018",
        "start_date": "2018-03-11T19:30+05:30",
        "event_format": "t20",
        "event_stage": "league"
      },
      {
        "event_status": "Match Ended",
        "series_id": "2957",
        "event_is_daynight": "true",
        "event_state": "R",
        "result_code": "W",
        "event_islinkable": "true",
        "event_status_id": "114",
        "result_sub_code": "",
        "event_priority": "",
        "event_day": "",
        "league_code": "indian_domestic",
        "venue_id": "168",
        "event_sub_status": "NaMo Bandra Blasters beat Shivaji Park Lions by 12 runs",
        "event_livecoverage": "true",
        "event_duration_left": "",
        "game_id": "scrncr03122018186402",
        "participants": [
          {
            "name": "Shivaji Park Lions",
            "short_name": "SPL",
            "id": "1633",
            "value": "170/9 (20)",
            "now": "true"
          },
          {
            "name": "NaMo Bandra Blasters",
            "short_name": "NBB",
            "id": "1630",
            "value": "182/5 (20)",
            "highlight": "true",
            "firstup": "true"
          }
        ],
        "tour_id": "876",
        "end_date": "2018-03-12T19:30+05:30",
        "venue_gmt_offset": "+05:30",
        "winning_margin": "12 runs",
        "venue_name": "Wankhede Stadium, Mumbai",
        "event_group": "",
        "event_name": "Match 3",
        "event_session": "",
        "series_name": "T20 Mumbai, 2018",
        "sport": "cricket",
        "tour_name": "T20 Mumbai, 2018",
        "start_date": "2018-03-12T15:30+05:30",
        "event_format": "t20",
        "event_stage": "league"
      },
      {
        "event_status": "Match Ended",
        "series_id": "2957",
        "event_is_daynight": "true",
        "event_state": "R",
        "result_code": "W",
        "event_islinkable": "true",
        "event_status_id": "114",
        "result_sub_code": "",
        "event_priority": "",
        "event_day": "",
        "league_code": "indian_domestic",
        "venue_id": "168",
        "event_sub_status": "SoBo SuperSonics beat North Mumbai Panthers by 3 wickets",
        "event_livecoverage": "true",
        "event_duration_left": "",
        "game_id": "mszmnz03122018186403",
        "participants": [
          {
            "name": "SoBo SuperSonics",
            "short_name": "SS",
            "id": "1634",
            "value": "198/7 (19.1)",
            "now": "true",
            "highlight": "true"
          },
          {
            "name": "North Mumbai Panthers",
            "short_name": "NMP",
            "id": "1629",
            "value": "192/4 (20)",
            "firstup": "true"
          }
        ],
        "tour_id": "876",
        "end_date": "2018-03-12T23:30+05:30",
        "venue_gmt_offset": "+05:30",
        "winning_margin": "3 wickets",
        "venue_name": "Wankhede Stadium, Mumbai",
        "event_group": "",
        "event_name": "Match 4",
        "event_session": "",
        "series_name": "T20 Mumbai, 2018",
        "sport": "cricket",
        "tour_name": "T20 Mumbai, 2018",
        "start_date": "2018-03-12T19:30+05:30",
        "event_format": "t20",
        "event_stage": "league"
      },
      {
        "event_status": "Match Ended",
        "series_id": "2957",
        "event_is_daynight": "true",
        "event_state": "R",
        "result_code": "W",
        "event_islinkable": "true",
        "event_status_id": "114",
        "result_sub_code": "",
        "event_priority": "",
        "event_day": "",
        "league_code": "indian_domestic",
        "venue_id": "168",
        "event_sub_status": "Shivaji Park Lions beat Triumph Knights Mumbai North East by 7 wickets",
        "event_livecoverage": "true",
        "event_duration_left": "",
        "game_id": "scrnte03132018186404",
        "participants": [
          {
            "name": "Shivaji Park Lions",
            "short_name": "SPL",
            "id": "1633",
            "value": "157/3 (19.1)",
            "now": "true",
            "highlight": "true"
          },
          {
            "name": "Triumph Knights Mumbai North East",
            "short_name": "TKMNE",
            "id": "1632",
            "value": "152 (19.5)",
            "firstup": "true"
          }
        ],
        "tour_id": "876",
        "end_date": "2018-03-13T19:30+05:30",
        "venue_gmt_offset": "+05:30",
        "winning_margin": "7 wickets",
        "venue_name": "Wankhede Stadium, Mumbai",
        "event_group": "",
        "event_name": "Match 5",
        "event_session": "",
        "series_name": "T20 Mumbai, 2018",
        "sport": "cricket",
        "tour_name": "T20 Mumbai, 2018",
        "start_date": "2018-03-13T15:30+05:30",
        "event_format": "t20",
        "event_stage": "league"
      },
      {
        "event_status": "Match Ended",
        "series_id": "2957",
        "event_is_daynight": "true",
        "event_state": "R",
        "result_code": "W",
        "event_islinkable": "true",
        "event_status_id": "114",
        "result_sub_code": "",
        "event_priority": "",
        "event_day": "",
        "league_code": "indian_domestic",
        "venue_id": "168",
        "event_sub_status": "NaMo Bandra Blasters beat ARCS Andheri by 9 wickets",
        "event_livecoverage": "true",
        "event_duration_left": "",
        "game_id": "mntncr03132018186405",
        "participants": [
          {
            "name": "ARCS Andheri",
            "short_name": "AA",
            "id": "1631",
            "value": "107 (19)",
            "firstup": "true"
          },
          {
            "name": "NaMo Bandra Blasters",
            "short_name": "NBB",
            "id": "1630",
            "value": "108/1 (13.2)",
            "now": "true",
            "highlight": "true"
          }
        ],
        "tour_id": "876",
        "end_date": "2018-03-13T23:30+05:30",
        "venue_gmt_offset": "+05:30",
        "winning_margin": "9 wickets",
        "venue_name": "Wankhede Stadium, Mumbai",
        "event_group": "",
        "event_name": "Match 6",
        "event_session": "",
        "series_name": "T20 Mumbai, 2018",
        "sport": "cricket",
        "tour_name": "T20 Mumbai, 2018",
        "start_date": "2018-03-13T19:30+05:30",
        "event_format": "t20",
        "event_stage": "league"
      },
      {
        "event_status": "Match Ended",
        "series_id": "2957",
        "event_is_daynight": "true",
        "event_state": "R",
        "result_code": "W",
        "event_islinkable": "true",
        "event_status_id": "114",
        "result_sub_code": "",
        "event_priority": "",
        "event_day": "",
        "league_code": "indian_domestic",
        "venue_id": "168",
        "event_sub_status": "Triumph Knights Mumbai North East beat ARCS Andheri by 7 wickets",
        "event_livecoverage": "true",
        "event_duration_left": "",
        "game_id": "ntemnt03142018186406",
        "participants": [
          {
            "name": "Triumph Knights Mumbai North East",
            "short_name": "TKMNE",
            "id": "1632",
            "value": "117/3 (15.3)",
            "now": "true",
            "highlight": "true"
          },
          {
            "name": "ARCS Andheri",
            "short_name": "AA",
            "id": "1631",
            "value": "116 (19.1)",
            "firstup": "true"
          }
        ],
        "tour_id": "876",
        "end_date": "2018-03-14T23:30+05:30",
        "venue_gmt_offset": "+05:30",
        "winning_margin": "7 wickets",
        "venue_name": "Wankhede Stadium, Mumbai",
        "event_group": "",
        "event_name": "Match 7",
        "event_session": "",
        "series_name": "T20 Mumbai, 2018",
        "sport": "cricket",
        "tour_name": "T20 Mumbai, 2018",
        "start_date": "2018-03-14T19:30+05:30",
        "event_format": "t20",
        "event_stage": "league"
      },
      {
        "event_status": "Match Ended",
        "series_id": "2957",
        "event_is_daynight": "true",
        "event_state": "R",
        "result_code": "W",
        "event_islinkable": "true",
        "event_status_id": "114",
        "result_sub_code": "",
        "event_priority": "",
        "event_day": "",
        "league_code": "indian_domestic",
        "venue_id": "168",
        "event_sub_status": "SoBo SuperSonics beat NaMo Bandra Blasters by 50 runs",
        "event_livecoverage": "true",
        "event_duration_left": "",
        "game_id": "ncrmsz03152018186407",
        "participants": [
          {
            "name": "NaMo Bandra Blasters",
            "short_name": "NBB",
            "id": "1630",
            "value": "99/9 (18)",
            "now": "true"
          },
          {
            "name": "SoBo SuperSonics",
            "short_name": "SS",
            "id": "1634",
            "value": "149/6 (18)",
            "highlight": "true",
            "firstup": "true"
          }
        ],
        "tour_id": "876",
        "end_date": "2018-03-15T19:30+05:30",
        "venue_gmt_offset": "+05:30",
        "winning_margin": "50 runs",
        "venue_name": "Wankhede Stadium, Mumbai",
        "event_group": "",
        "event_name": "Match 8",
        "event_session": "",
        "series_name": "T20 Mumbai, 2018",
        "sport": "cricket",
        "tour_name": "T20 Mumbai, 2018",
        "start_date": "2018-03-15T15:30+05:30",
        "event_format": "t20",
        "event_stage": "league"
      },
      {
        "event_status": "Match Ended",
        "series_id": "2957",
        "event_is_daynight": "true",
        "event_state": "R",
        "result_code": "W",
        "event_islinkable": "true",
        "event_status_id": "114",
        "result_sub_code": "",
        "event_priority": "",
        "event_day": "",
        "league_code": "indian_domestic",
        "venue_id": "168",
        "event_sub_status": "North Mumbai Panthers beat Shivaji Park Lions by 5 wickets",
        "event_livecoverage": "true",
        "event_duration_left": "",
        "game_id": "mnzscr03152018186408",
        "participants": [
          {
            "name": "North Mumbai Panthers",
            "short_name": "NMP",
            "id": "1629",
            "value": "138/5 (19.4)",
            "now": "true",
            "highlight": "true"
          },
          {
            "name": "Shivaji Park Lions",
            "short_name": "SPL",
            "id": "1633",
            "value": "135/9 (20)",
            "firstup": "true"
          }
        ],
        "tour_id": "876",
        "end_date": "2018-03-15T23:30+05:30",
        "venue_gmt_offset": "+05:30",
        "winning_margin": "5 wickets",
        "venue_name": "Wankhede Stadium, Mumbai",
        "event_group": "",
        "event_name": "Match 9",
        "event_session": "",
        "series_name": "T20 Mumbai, 2018",
        "sport": "cricket",
        "tour_name": "T20 Mumbai, 2018",
        "start_date": "2018-03-15T19:30+05:30",
        "event_format": "t20",
        "event_stage": "league"
      },
      {
        "event_status": "Match Ended",
        "series_id": "2957",
        "event_is_daynight": "true",
        "event_state": "R",
        "result_code": "W",
        "event_islinkable": "true",
        "event_status_id": "114",
        "result_sub_code": "",
        "event_priority": "",
        "event_day": "",
        "league_code": "indian_domestic",
        "venue_id": "168",
        "event_sub_status": "Triumph Knights Mumbai North East beat NaMo Bandra Blasters by 5 wickets",
        "event_livecoverage": "true",
        "event_duration_left": "",
        "game_id": "ntencr03162018186409",
        "participants": [
          {
            "name": "Triumph Knights Mumbai North East",
            "short_name": "TKMNE",
            "id": "1632",
            "value": "184/5 (20)",
            "now": "true",
            "highlight": "true"
          },
          {
            "name": "NaMo Bandra Blasters",
            "short_name": "NBB",
            "id": "1630",
            "value": "183/5 (20)",
            "firstup": "true"
          }
        ],
        "tour_id": "876",
        "end_date": "2018-03-16T19:30+05:30",
        "venue_gmt_offset": "+05:30",
        "winning_margin": "5 wickets",
        "venue_name": "Wankhede Stadium, Mumbai",
        "event_group": "",
        "event_name": "Match 10",
        "event_session": "",
        "series_name": "T20 Mumbai, 2018",
        "sport": "cricket",
        "tour_name": "T20 Mumbai, 2018",
        "start_date": "2018-03-16T15:30+05:30",
        "event_format": "t20",
        "event_stage": "league"
      },
      {
        "event_status": "Match Ended",
        "series_id": "2957",
        "event_is_daynight": "true",
        "event_state": "R",
        "result_code": "W",
        "event_islinkable": "true",
        "event_status_id": "114",
        "result_sub_code": "",
        "event_priority": "",
        "event_day": "",
        "league_code": "indian_domestic",
        "venue_id": "168",
        "event_sub_status": "Shivaji Park Lions beat ARCS Andheri by 6 wickets",
        "event_livecoverage": "true",
        "event_duration_left": "",
        "game_id": "scrmnt03162018186410",
        "participants": [
          {
            "name": "Shivaji Park Lions",
            "short_name": "SPL",
            "id": "1633",
            "value": "150/4 (18.2)",
            "now": "true",
            "highlight": "true"
          },
          {
            "name": "ARCS Andheri",
            "short_name": "AA",
            "id": "1631",
            "value": "149/8 (20)",
            "firstup": "true"
          }
        ],
        "tour_id": "876",
        "end_date": "2018-03-16T23:30+05:30",
        "venue_gmt_offset": "+05:30",
        "winning_margin": "6 wickets",
        "venue_name": "Wankhede Stadium, Mumbai",
        "event_group": "",
        "event_name": "Match 11",
        "event_session": "",
        "series_name": "T20 Mumbai, 2018",
        "sport": "cricket",
        "tour_name": "T20 Mumbai, 2018",
        "start_date": "2018-03-16T19:30+05:30",
        "event_format": "t20",
        "event_stage": "league"
      },
      {
        "event_status": "Match Ended",
        "series_id": "2957",
        "event_is_daynight": "true",
        "event_state": "R",
        "result_code": "W",
        "event_islinkable": "true",
        "event_status_id": "114",
        "result_sub_code": "",
        "event_priority": "",
        "event_day": "",
        "league_code": "indian_domestic",
        "venue_id": "168",
        "event_sub_status": "Triumph Knights Mumbai North East beat North Mumbai Panthers by 34 runs",
        "event_livecoverage": "true",
        "event_duration_left": "",
        "game_id": "mnznte03172018186411",
        "participants": [
          {
            "name": "North Mumbai Panthers",
            "short_name": "NMP",
            "id": "1629",
            "value": "145/8 (20)",
            "now": "true"
          },
          {
            "name": "Triumph Knights Mumbai North East",
            "short_name": "TKMNE",
            "id": "1632",
            "value": "179/8 (20)",
            "highlight": "true",
            "firstup": "true"
          }
        ],
        "tour_id": "876",
        "end_date": "2018-03-17T19:30+05:30",
        "venue_gmt_offset": "+05:30",
        "winning_margin": "34 runs",
        "venue_name": "Wankhede Stadium, Mumbai",
        "event_group": "",
        "event_name": "Match 12",
        "event_session": "",
        "series_name": "T20 Mumbai, 2018",
        "sport": "cricket",
        "tour_name": "T20 Mumbai, 2018",
        "start_date": "2018-03-17T15:30+05:30",
        "event_format": "t20",
        "event_stage": "league"
      },
      {
        "event_status": "Match Ended",
        "series_id": "2957",
        "event_is_daynight": "true",
        "event_state": "R",
        "result_code": "W",
        "event_islinkable": "true",
        "event_status_id": "114",
        "result_sub_code": "",
        "event_priority": "",
        "event_day": "",
        "league_code": "indian_domestic",
        "venue_id": "168",
        "event_sub_status": "SoBo SuperSonics beat ARCS Andheri by 78 runs",
        "event_livecoverage": "true",
        "event_duration_left": "",
        "game_id": "mntmsz03172018186412",
        "participants": [
          {
            "name": "ARCS Andheri",
            "short_name": "AA",
            "id": "1631",
            "value": "158 (18.3)",
            "now": "true"
          },
          {
            "name": "SoBo SuperSonics",
            "short_name": "SS",
            "id": "1634",
            "value": "236/3 (20)",
            "highlight": "true",
            "firstup": "true"
          }
        ],
        "tour_id": "876",
        "end_date": "2018-03-17T23:30+05:30",
        "venue_gmt_offset": "+05:30",
        "winning_margin": "78 runs",
        "venue_name": "Wankhede Stadium, Mumbai",
        "event_group": "",
        "event_name": "Match 13",
        "event_session": "",
        "series_name": "T20 Mumbai, 2018",
        "sport": "cricket",
        "tour_name": "T20 Mumbai, 2018",
        "start_date": "2018-03-17T19:30+05:30",
        "event_format": "t20",
        "event_stage": "league"
      },
      {
        "event_status": "Match Ended",
        "series_id": "2957",
        "event_is_daynight": "true",
        "event_state": "R",
        "result_code": "W",
        "event_islinkable": "true",
        "event_status_id": "114",
        "result_sub_code": "",
        "event_priority": "",
        "event_day": "",
        "league_code": "indian_domestic",
        "venue_id": "168",
        "event_sub_status": "NaMo Bandra Blasters beat North Mumbai Panthers by 10 wickets",
        "event_livecoverage": "true",
        "event_duration_left": "",
        "game_id": "ncrmnz03182018186413",
        "participants": [
          {
            "name": "NaMo Bandra Blasters",
            "short_name": "NBB",
            "id": "1630",
            "value": "126/0 (11.3)",
            "now": "true",
            "highlight": "true"
          },
          {
            "name": "North Mumbai Panthers",
            "short_name": "NMP",
            "id": "1629",
            "value": "125/9 (20)",
            "firstup": "true"
          }
        ],
        "tour_id": "876",
        "end_date": "2018-03-18T19:30+05:30",
        "venue_gmt_offset": "+05:30",
        "winning_margin": "10 wickets",
        "venue_name": "Wankhede Stadium, Mumbai",
        "event_group": "",
        "event_name": "Match 14",
        "event_session": "",
        "series_name": "T20 Mumbai, 2018",
        "sport": "cricket",
        "tour_name": "T20 Mumbai, 2018",
        "start_date": "2018-03-18T15:30+05:30",
        "event_format": "t20",
        "event_stage": "league"
      },
      {
        "event_status": "Match Ended",
        "series_id": "2957",
        "event_is_daynight": "true",
        "event_state": "R",
        "result_code": "W",
        "event_islinkable": "true",
        "event_status_id": "114",
        "result_sub_code": "",
        "event_priority": "",
        "event_day": "",
        "league_code": "indian_domestic",
        "venue_id": "168",
        "event_sub_status": "SoBo SuperSonics beat Shivaji Park Lions by 3 wickets",
        "event_livecoverage": "true",
        "event_duration_left": "",
        "game_id": "mszscr03182018186414",
        "participants": [
          {
            "name": "SoBo SuperSonics",
            "short_name": "SS",
            "id": "1634",
            "value": "154/7 (20)",
            "now": "true",
            "highlight": "true"
          },
          {
            "name": "Shivaji Park Lions",
            "short_name": "SPL",
            "id": "1633",
            "value": "150/7 (20)",
            "firstup": "true"
          }
        ],
        "tour_id": "876",
        "end_date": "2018-03-18T23:30+05:30",
        "venue_gmt_offset": "+05:30",
        "winning_margin": "3 wickets",
        "venue_name": "Wankhede Stadium, Mumbai",
        "event_group": "",
        "event_name": "Match 15",
        "event_session": "",
        "series_name": "T20 Mumbai, 2018",
        "sport": "cricket",
        "tour_name": "T20 Mumbai, 2018",
        "start_date": "2018-03-18T19:30+05:30",
        "event_format": "t20",
        "event_stage": "league"
      },
      {
        "event_status": "Match Ended",
        "series_id": "2957",
        "event_is_daynight": "true",
        "event_state": "R",
        "result_code": "W",
        "event_islinkable": "true",
        "event_status_id": "114",
        "result_sub_code": "",
        "event_priority": "",
        "event_day": "",
        "league_code": "indian_domestic",
        "venue_id": "168",
        "event_sub_status": "Triumph Knights Mumbai North East beat SoBo SuperSonics by 40 runs",
        "event_livecoverage": "true",
        "event_duration_left": "",
        "game_id": "msznte03192018186415",
        "participants": [
          {
            "name": "SoBo SuperSonics",
            "short_name": "SS",
            "id": "1634",
            "value": "122 (19.1)",
            "now": "true"
          },
          {
            "name": "Triumph Knights Mumbai North East",
            "short_name": "TKMNE",
            "id": "1632",
            "value": "162/6 (20)",
            "highlight": "true",
            "firstup": "true"
          }
        ],
        "tour_id": "876",
        "end_date": "2018-03-19T19:30+05:30",
        "venue_gmt_offset": "+05:30",
        "winning_margin": "40 runs",
        "venue_name": "Wankhede Stadium, Mumbai",
        "event_group": "",
        "event_name": "Qualifier 1",
        "event_session": "",
        "series_name": "T20 Mumbai, 2018",
        "sport": "cricket",
        "tour_name": "T20 Mumbai, 2018",
        "start_date": "2018-03-19T15:30+05:30",
        "event_format": "t20",
        "event_stage": "playoffs"
      },
      {
        "event_status": "Match Ended",
        "series_id": "2957",
        "event_is_daynight": "true",
        "event_state": "R",
        "result_code": "W",
        "event_islinkable": "true",
        "event_status_id": "114",
        "result_sub_code": "",
        "event_priority": "",
        "event_day": "",
        "league_code": "indian_domestic",
        "venue_id": "168",
        "event_sub_status": "Shivaji Park Lions beat NaMo Bandra Blasters by 6 wickets",
        "event_livecoverage": "true",
        "event_duration_left": "",
        "game_id": "ncrscr03192018186416",
        "participants": [
          {
            "name": "NaMo Bandra Blasters",
            "short_name": "NBB",
            "id": "1630",
            "value": "169/4 (20)",
            "firstup": "true"
          },
          {
            "name": "Shivaji Park Lions",
            "short_name": "SPL",
            "id": "1633",
            "value": "172/4 (17.4)",
            "now": "true",
            "highlight": "true"
          }
        ],
        "tour_id": "876",
        "end_date": "2018-03-19T23:30+05:30",
        "venue_gmt_offset": "+05:30",
        "winning_margin": "6 wickets",
        "venue_name": "Wankhede Stadium, Mumbai",
        "event_group": "",
        "event_name": "Eliminator",
        "event_session": "",
        "series_name": "T20 Mumbai, 2018",
        "sport": "cricket",
        "tour_name": "T20 Mumbai, 2018",
        "start_date": "2018-03-19T19:30+05:30",
        "event_format": "t20",
        "event_stage": ""
      },
      {
        "event_status": "Match Ended",
        "series_id": "2957",
        "event_is_daynight": "true",
        "event_state": "R",
        "result_code": "W",
        "event_islinkable": "true",
        "event_status_id": "114",
        "result_sub_code": "",
        "event_priority": "",
        "event_day": "",
        "league_code": "indian_domestic",
        "venue_id": "168",
        "event_sub_status": "Shivaji Park Lions beat SoBo SuperSonics by 6 wickets",
        "event_livecoverage": "true",
        "event_duration_left": "",
        "game_id": "mszscr03202018186417",
        "participants": [
          {
            "name": "SoBo SuperSonics",
            "short_name": "SS",
            "id": "1634",
            "value": "194/7 (20)",
            "firstup": "true"
          },
          {
            "name": "Shivaji Park Lions",
            "short_name": "SPL",
            "id": "1633",
            "value": "195/4 (17.5)",
            "now": "true",
            "highlight": "true"
          }
        ],
        "tour_id": "876",
        "end_date": "2018-03-20T23:30+05:30",
        "venue_gmt_offset": "+05:30",
        "winning_margin": "6 wickets",
        "venue_name": "Wankhede Stadium, Mumbai",
        "event_group": "",
        "event_name": "Qualifier 2",
        "event_session": "",
        "series_name": "T20 Mumbai, 2018",
        "sport": "cricket",
        "tour_name": "T20 Mumbai, 2018",
        "start_date": "2018-03-20T19:30+05:30",
        "event_format": "t20",
        "event_stage": "playoffs"
      },
      {
        "event_status": "Match Ended",
        "series_id": "2957",
        "event_is_daynight": "true",
        "event_state": "R",
        "result_code": "W",
        "event_islinkable": "true",
        "event_status_id": "114",
        "result_sub_code": "",
        "event_priority": "",
        "event_day": "",
        "league_code": "indian_domestic",
        "venue_id": "168",
        "event_sub_status": "Triumph Knights Mumbai North East beat Shivaji Park Lions by 3 runs",
        "event_livecoverage": "true",
        "event_duration_left": "",
        "game_id": "ntescr03212018186418",
        "participants": [
          {
            "name": "Triumph Knights Mumbai North East",
            "short_name": "TKMNE",
            "id": "1632",
            "value": "182/5 (20)",
            "highlight": "true",
            "firstup": "true"
          },
          {
            "name": "Shivaji Park Lions",
            "short_name": "SPL",
            "id": "1633",
            "value": "179/8 (20)",
            "now": "true"
          }
        ],
        "tour_id": "876",
        "end_date": "2018-03-21T23:30+05:30",
        "venue_gmt_offset": "+05:30",
        "winning_margin": "3 runs",
        "venue_name": "Wankhede Stadium, Mumbai",
        "event_group": "",
        "event_name": "Final",
        "event_session": "",
        "series_name": "T20 Mumbai, 2018",
        "sport": "cricket",
        "tour_name": "T20 Mumbai, 2018",
        "start_date": "2018-03-21T19:30+05:30",
        "event_format": "t20",
        "event_stage": "final"
      }
    ]
  }
  